name: Flight Delay Predictor CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtualenv + install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install kaggle pytest pytest-cov flake8 black

      - name: Download dataset from Kaggle
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}
        run: |
          source venv/bin/activate
          mkdir -p ~/.kaggle
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          kaggle datasets download -d usdot/flight-delays -p data/raw --unzip
          ls -la data/raw

      - name: Prepare processed data
        run: |
          source venv/bin/activate
          python app/preprocess/prepare_training_data.py

      - name: Run code linting
        run: |
          source venv/bin/activate
          flake8 app tests

      - name: Train model (Prefect flow)
        run: |
          source venv/bin/activate
          python app/etl/train_flow.py

      - name: Run unit tests with coverage
        run: |
          source venv/bin/activate
          pytest --cov=app --cov-report=xml

      - name: Check if model file exists
        run: |
          test -f models/lgbm_model.pkl

      - name: Upload trained model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lgbm_model
          path: models/lgbm_model.pkl
